dump_dir: "./apps/main/ntp_llama_512"  
name: ntp_llama_512
steps: 15_300 # one epoch is 3051 steps with batch_size: 16!
seed: 777

optim:
  lr: 3e-3
  weight_decay: 0.033 
  warmup: 1000 #~5% of total steps for gradual learning rate increase from 1000
  lr_min_ratio: 0.000001 # 1e-6
  clip: 1.0

distributed:
  fsdp_type: full_shard
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  tp_size: 1

model:
  dim: 512
  n_layers: 10
  n_heads: 8
  #n_future_head: 3

data:
  root_dir: ./babylm_data_json
  sources:
    babylm_100M_clean_json: 1.0
  batch_size: 64
  prefetch_size: 256 #how many batches of data are loaded into memory in advance -> maybe increase?
  seq_len: 512
  n_views: 2 # because always:`n_future_head == n_views - 1`
  load_async: true
  add_bos: true
  add_eos: true
  tokenizer:
    name: tiktoken
    path: "./tokenizers/llama3/original/tokenizer.model"

profiling:
  run: true
  mem_warmup: 0
  mem_steps: 4
  profile_warmup: 100
  profile_steps: 4

checkpoint:
  dump:
    every: 3000
    keep: 5
  eval:
    every: 5000
    keep: -1

logging:
  freq: 1
  # wandb: null??

# async_eval_gpus: null
# eval:
#   harness:
#     tasks:
#       - hellaswag
#       # - nq_open
#       # - piqa
#       # - siqa
#       # - csatqa
#       # - winogrande
#       # - arc
#       # - race
#       # - gsm8k
#       # - bbh
#       # - mmlu
#   generator:
#     max_tokens: 16384
#     dtype: bf16
