name: "generate_eval"
dump_dir: "./apps/mtp/output_grammar"
# metric_log_dir: str OPTIONAL
ckpt_dir: "./apps/mtp/output_grammar_2_M/checkpoints/0000013200"
generator:
  max_tokens: 8192
  dtype: bf16
  temperature: 1.0
  top_p: 0.95
harness:
  tasks:
    - hellaswag
    - task: boolq
      dataset_kwargs:
        trust_remote_code: true
    - task: nq_open
      num_fewshot: 5
  # - piqa
  # - siqa
  # - tqa
  # - winogrande
  # - obqa
  # - arc_easy
  # - arc_challenge
  # - race_middle
  # - race_high
  # - gsm8k
  # - bbh
  # - copa
  # - human_eval_plus
  # - mbpp
  # - mmlu
