name: "generate_grammar"
dump_dir: "./apps/mtp/output_grammar"
# metric_log_dir: str OPTIONAL
#ckpt_dir: "./apps/mtp/output_grammar_2_M/checkpoints/0000013200"


generator:
  # main.generate.PackedCausalTransformerGeneratorArgs
  temperature: 1.0
  top_p: None
  top_k: None
  max_gen_len: 100 # Maximum generation length
  max_tokens: 50 # Maximum number of tokens that can go through the model
  max_prompt_len: 100 #Change1 or delete
  dtype: bf16

single_prompt: "Write a sentence about the sun"

  
# harness:
#   tasks:
#     - hellaswag
#     - task: boolq
#       dataset_kwargs:
#         trust_remote_code: true


