dump_dir: "./apps/mtp/output_grammar_test"  # Updated for grammar evaluation focus
name: "grammar_test_small"
steps: 3000
probe_freq: null
seed: 777

optim:
  lr: 3e-4 # maybe change to 2e-4
  weight_decay: 0.01  # Light regularization to prevent overfitting on limited data
  warmup: 1000  # Adjusted to a higher warmup relative to total steps
  lr_min_ratio: 0.000001
  clip: 10.0

distributed:
  fsdp_type: full_shard
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  tp_size: 1

model:
  dim: 768
  n_layers: 6
  n_heads: 6
  n_future_head: 3

data:
  root_dir: "./babylm_data/babylm_10M_shuffled"
  sources:
    fineweb_edu_tiny: 1.0
  batch_size: 4
  prefetch_size: 16
  seq_len: 256
  n_views: 4
  load_async: true
  add_bos: true
  add_eos: true
  tokenizer:
    name: tiktoken
    path: "./tokenizers/llama3/original/tokenizer.model"

profiling:
  run: true
  mem_warmup: 0
  mem_steps: 4
  profile_warmup: 100
  profile_steps: 4

checkpoint:
  dump:
    every: 200
    keep: 3
  eval:
    every: 500
    keep: 2

logging:
  freq: 20  # Moderate logging frequency to focus on significant updates

async_eval_gpus: 1  # Reduced for small-scale testing
# eval:
#   harness:
#     tasks: []  # No external benchmarks; focus on generator output
#   generator:
#     max_tokens: 1024  # Increased to allow evaluation of longer sentence outputs
#     dtype: bf16
#     temperature: 0.8  # Adjusted to encourage diverse yet coherent outputs
#     top_p: 0.95
